[package]
name = "termbox"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"] }
anyhow = "1"
const-str = "0.6.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
futures = "0.3"
